name Geração de Releases

on
  push
    branches
      - master

jobs
  build
    runs-on ubuntu-latest
    
    steps
      - name Checkout do repositório
        uses actionscheckout@v2

      - name Configuração do ambiente Java
        uses actionssetup-java@v2
        with
          java-version '11'
          distribution 'adopt'

      - name Compilação e geração do APK
        run .gradlew assembleRelease

      - name Upload do APK
        uses actionsupload-release-asset@v1
        with
          asset_path appbuildoutputsapkreleaseapp-release.apk
          asset_name app-release.apk
          asset_content_type applicationvnd.android.package-archive
